apiVersion: apps/v1
kind: Deployment
metadata:
  name: kurrent-ocr-api
  labels:
    app: kurrent-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kurrent-ocr-api
  template:
    metadata:
      labels:
        app: kurrent-ocr-api
    spec:
      containers:
      - name: api
        # Updated to match your 'docker images' output
        image: kurrent_ocr-kurrent-api:latest
        # Vital for local images to prevent "Pull" errors
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1

