name: kurrent
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - numpy=1.26
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - numpy<2
      - transformers==4.36.2
      - fastapi
      - uvicorn
      - python-multipart
      - opencv-python-headless
      - safetensors
      - sentencepiece
      - accelerate
      - pillow
      - scipy